# Generated by Django 5.0.8 on 2024-08-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
