# Generated by Django 5.0.8 on 2024-08-07 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_myblog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myblog',
            old_name='image',
            new_name='Image',
        ),
    ]
