# Generated by Django 5.0.8 on 2024-08-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_rename_image_myblog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myblog',
            old_name='Image',
            new_name='image',
        ),
    ]
