# Generated by Django 5.0.8 on 2024-08-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_rename_image_myblog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
