# Generated by Django 5.0.8 on 2024-08-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_myblog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
