# Generated by Django 5.0.8 on 2024-08-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_alter_myblog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblog',
            name='date',
        ),
    ]
