# Generated by Django 5.0.8 on 2024-08-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_remove_myblog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
